/*
Name: Madilyn Carpenter
Date: 12/14/2025
Assignment 2
Purpose: Read and display contents of dat file generated by WriteData class.
*/

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class ReadData {

    public static void main(String[] args) {
        String filename = "MadilynCarpenter_datafile.dat";

        try {
            File file = new File(filename);
            Scanner scanner = new Scanner(file);

            System.out.println("Contents of " + filename + " file: ");

            // Read contents of dat file
            while (scanner.hasNextLine()) {
                System.out.println(scanner.nextLine());
            }

            scanner.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found.");
            e.printStackTrace();
        }
    }
}
